### ISSUE TITLE
Rebrand screenshot.png

### ISSUE THREAD

**Issue by mattada** [factor1/Prelude#22]
New artwork coming for the Prelude branded screenshot. 
Prelude/src/screenshot.png
![screenshot](https://cloud.githubusercontent.com/assets/10223806/12178382/64aaeb26-b52e-11e5-86ed-7a61406caa26.png)

**Comment by buschschwick** [comment]
This isn't managed by any Gulp settings, so you can add this whenever you want or send to me. Either way.
