### ISSUE TITLE
Copy Task Discussion

### ISSUE THREAD

**Issue by buschschwick** [factor1/Prelude#24]
Currently the `copy` gulp task is part of the `default` gulp task. So when you run `gulp` or `gulp default` it copies the essential files to the `theme-name` folder for distribution.

My thought is maybe this should be removed and only used when ready. Thoughts? 

@bebaps

**Comment by bebaps** [comment]
@buschschwick I agree. I am a fan of taking more of a separation of concerns approach, and bundling tasks (and sub tasks) where it makes sense to do so. This way we can test the tasks individually and when we know they work as expected under any given condition, then we can make the decision to either bundle them together with other related tasks, or to just chain them together as needed.

**Comment by buschschwick** [comment]
The `copy` task was destroyed in the `default`  task in `2.2.0`
