### ISSUE TITLE
Major Update: Possibly Kill src and dist folders?

### ISSUE THREAD

**Issue by erwstout** [factor1/Prelude#30]
We may not need to have two folders any longer, and with some gulp task rewrites it may make it not needed.

**Comment by erwstout** [comment]
Does anyone have any issues with creating a single folder structure? The `gulpfile.js` would just be modified to compile inside itself.

This would be highly beneficial because it would reduce the size of the repos by half, and would also make it extremely easy to push to remote repos since we are going toward that style of management. 

@mattada @bebaps

**Comment by bebaps** [comment]
Im coo with that

**Comment by mattada** [comment]
Council has spoken. Approved.

**Comment by erwstout** [comment]
🤘

**Comment by erwstout** [comment]
Almost good to go. Just need to update documentations then `3.0.0` will be pushed live.
