### ISSUE TITLE
Remove Footer Class

### ISSUE THREAD

**Issue by erwstout** [factor1/Prelude#34]
Remove class of `footer` from `<footer>` - adding class is redundant.

**Comment by bebaps** [comment]
I disagree. Footers can be added in any `div`, `section`, `article`, `aside`, in another `footer`, etc. That class is there to still make sure we target the correct footer and not sitewide.

**Comment by erwstout** [comment]
Yes, you can include multiple footers in a project, however by default we are only using one. If we were going to give the `<footer>` a class by default the naming convention should be more specific. A class of `footer` doesn't really tell us anymore information then `<footer>` does, so it would be more along the lines of `<footer class="site-footer">` or `default-footer`, something that aligns with what the footer function is.

Aside from naming conventions, I don't think the `<footer>` in `footer.php` should have a class at all, since we are only focusing on structure and we aren't using the class for anything by default.

**Comment by mattada** [comment]
I think from a default set up, `<footer>` isn the footer.php is all we need to plan for in this setup. IF and WHEN its needed to have multiple footers in a document, I would assume thats when you target them with css specifically. Even then, I lean to SCSS to mange an article footer separately from the root footer elements.

**Comment by erwstout** [comment]
Completed in forthcoming patch
