### ISSUE TITLE
Remove Favicon from `header.php`?

### ISSUE THREAD

**Issue by erwstout** [factor1/Prelude#40]
Given that WordPress now has a native function to upload a logo for favicon usage, would it be wise to remove this line from `header.php`:

```html
<link rel="shortcut icon" href="/favicon.ico" type="image/x-icon" />
```

@factor1/staff

**Comment by bebaps** [comment]
I think that there isn't a favicon in the project anyway, yea get rid of it.

**Comment by erwstout** [comment]
Removed in `3.0.3`
